### PR TITLE
add link to rubydocs.org to documentation

### PR DESCRIPTION
**Pull request by manuelmeurer**
Hi @zzak! 😄 

I added Sinatra to RubyDocs.org, so I thought it would be nice to link to it from the Sinatra documentation page.

Cheers,
Manuel

### CODE REVIEW

**Comment by zzak** [comment]
Hello @manuelmeurer,

Isn't rubydoc.info also just as searchable? I'm not sure we need to link to both.

Sorry!

**Comment by manuelmeurer** [comment]
Yeah, maybe "Searchable API docs" is not the right name... some people prefer the "quick" search of sdoc over Yard, also RubyDocs lets you download the docs for offline use.

**Comment by zzak** [comment]
Sorry @manuelmeurer I'm going to give this a close.

I'd like to find a way to incorporate the API docs directly with the site build, for every version hereafter.

So that anyone using Sinatra can find the appropriate docs for their version immediately, without searching.

Thanks for your patch and keep up the good work.

If you'd like to help build the API docs into the site, let me know!

**Comment by manuelmeurer** [comment]
Yeah sure, I can help with that.
Where exactly do you want to store the docs? And do you want to generate them for each version of Sinatra (from the current version onwards) on each build of sinatra.github.com?

**Comment by manuelmeurer** [comment]
And do you want to generate sdoc or pure rdoc? 😄

**Pull request closed without merging**
