### PR TITLE
Index page redesign

### PR DESCRIPTION
**Pull request by vis-kid**
New responsive navbar
New code example
New bg design
Clean up and prep for further global changes
Add [Bourbon](http://bourbon.io/) / [Neat](http://neat.bourbon.io/) to the mix
Add [Gulp](http://gulpjs.com/) as build tool: compilation, minification, purification
Thanks @zzak !

### CODE REVIEW

**Comment by zzak** [comment]
Does it make sense to commit all of these node_modules?

I'm afraid of bloating the repo and making clone, etc a pain.

**Comment by vis-kid** [comment]
I’ll get rid of them then.

Future contributors who are unfamiliar with Gulp won’t be ready to use custom build tasks like “gulp build-css” or “gulp sass2css” out of the box then I guess…

But bloating the repo is definitely not something that I want to do of course.

**Comment by zzak** [comment]
@vis-kid Thanks! Could you squash then too? I think since the commit still exists in your branch it still affects the index size.

**Comment by vis-kid** [comment]
Squashed!

**Comment by vis-kid** [comment]
Fresh clone:
screen shot 2016-08-04 at 5 48 39 am

My branch:
screen shot 2016-08-04 at 5 48 53 am

**Comment by vis-kid** [comment]
Seems like index cleaning is in order, no? First time for everything :)

**Comment by vis-kid** [comment]
On the other hand, `git ls-files` doesn’t show any trace of node_modules in the index…

Guess the increase in index size is then mostly spiked by using [Bourbon](http://bourbon.io/) and [Neat](http://neat.bourbon.io/)—which are considered to be pretty lightweight though.

**Comment by zzak** [comment]
@vis-kid Can you push so that I can verify?

**Comment by vis-kid** [comment]
Pushed already :) Unless I misunderstood you should be able to verify already…

**Comment by zzak** [comment]
@vis-kid I think you squashed but you have to force push (git push -f origin branch) in order to update the PR

**Comment by vis-kid** [comment]
I did force push. `Everything up-to-date`

**Comment by vis-kid** [comment]
I squashed the latest two commits into one and kept the last commit message `Update gitignore to exclude node_modules`.

Was that a mistake?

**Comment by zzak** [comment]
No worries, let me see if I can fix it from my end and get this merged. Hang tight :)

**Comment by vis-kid** [comment]
If the index does not show a trace of the node_modules and they don’t show up in `files changed` plus the commit introducing the node_modules has been squashed and pushed, what needs fixing? :)

**Comment by zzak** [comment]
@vis-kid All fixed and merged!

I did a `filter-branch` using the following command:
`git filter-branch --index-filter   'git rm -rf --ignore-unmatch --cached node_modules'`

This got the repo down to 3.5MiB from 6.4MiB.

Before: `Receiving objects: 100% (6901/6901), 6.42 MiB | 993.00 KiB/s, done.`
After: `Receiving objects: 100% (3376/3376), 3.51 MiB | 1.61 MiB/s, done.`

**Pull request closed without merging**
