### PR TITLE
Add reference to JubiGems sinatra/static

### PR DESCRIPTION
**Pull request by jubishop**
Add reference to JubiGems (Sinatra App) and sinatra/static (Sinatra Library)

### CODE REVIEW

**Comment by zzak** [comment]
Hello @jubishop this is really cool, and I had a look through your profile which is filled with interesting things :)

I would prefer though if we just linked to the GitHub project, if you wouldn't mind changing your PR? :bow:

**Comment by jubishop** [comment]
The Sinatra-static link is in fact for GitHub?  Do you mean remove the reference to JubiGems?

**Comment by zzak** [comment]
@jubishop I mean to link to https://github.com/jubishop/jubigems instead of the main site.

I know this probably hasn't been followed carefully in the past, but linking to a domain that will often expire after a few years is less preferred than just linking to the code here on GitHub.

**Comment by jubishop** [comment]
Ohh I gotcha.  Coolio

**Comment by zzak** [comment]
@jubishop While you're in there would you mind adding a comment for future PRs to just link to the code instead of the domain?

**Pull request merged**
