### PR TITLE
Improve code highlighter on docs and configuration

### PR DESCRIPTION
**Pull request by vis-kid**
Add slight background-color, better text color and white text-shadow

See changes live [here](http://vis-kid.github.io/sinatra.github.com/configuration.html).

# Before
screen shot 2016-08-30 at 6 54 00 pm

# After
screen shot 2016-08-30 at 6 53 44 pm

### CODE REVIEW

**Comment by zzak** [comment]
@vis-kid Please rebase <3

**Comment by vis-kid** [comment]
done!

**Comment by zzak** [comment]
@vis-kid Needs a rebase, sorry for the slow response time

**Comment by vis-kid** [comment]
No problem! :)

**Comment by vis-kid** [comment]
@zzak done!

**Pull request merged**
