### PR TITLE
Update README.ko.html

### PR DESCRIPTION
**Pull request by pjc0247**

### CODE REVIEW

**Comment by kgrz** [comment]
Paging @marocchino. Need help with reviewing this PR

**Comment by marocchino** [comment]
:+1: for content. but, This PR should go to [the sinatra repo](https://github.com/sinatra/sinatra/blob/master/README.ko.md).

**Comment by kgrz** [comment]
Oh, I missed that part :facepalm:. @pjc0247 Can you open a PR onto the main sinatra (sinatra/sinatra) repo? You can simply edit the README.ko.md file therein. I'm gonna close this PR.

@marocchino Thank you for taking a look! :)

**Comment by pjc0247** [comment]
Okay, I made a [new one](https://github.com/sinatra/sinatra/pull/1067).

**Pull request closed without merging**
